### ISSUE TITLE
Pokemon Alpha Ruby Issue

### ISSUE THREAD

**Issue by EscanorXX** [SachinVin/citra_android#102]
Omega Ruby not alpha ruby*

I'm a Pocophone F1 owner and The game starts super smooth, showing colours and all. It lets me pick a language and when I click on "begin" to start playing, it crashes. Tried picking with all the languages and it does the same. Please help. I cannot play any 3DS pokemon game...

**Comment by Priyam005** [comment]
You might need the user folder..

**Comment by YasunaMC** [comment]
It works for me @EscanorXX folder with fonts etc

**Comment by YasunaMC** [comment]
If little child dont use its wip it will eat your pets or your self

**Comment by Priyam005** [comment]
@EscanorXX As YasunaMC said you need to dump the shared font.bin file to make Omega Ruby work

**Comment by EscanorXX** [comment]
Please tell me the instructions I really want to play tha game

**Comment by EscanorXX** [comment]
@Priyam005 **PLEASE, can you tell me the instructions to do it? **

**Comment by MinjeongMark** [comment]
is there any way to dump them without having to need the actual 3ds itself?

**Comment by melsbacksfriend** [comment]
I can't get the Android version to read the shared font.

**Comment by HelloOO7** [comment]
@MinjeongMark No. You need a 3DS to use Citra legally (unless you dump your games through someone else's 3DS). As Citra doesn't endorse piracy, we can't help you with that.

**Comment by EscanorXX** [comment]
@SachinVin non dump files needed. I disabled the hardwares shaders like @wannabeGDN said and it's working pretty good. It just need a 15% or 20% more speed and it would work super smooth!
