### ISSUE TITLE
save file location

### ISSUE THREAD

**Issue by 2maikel1** [SachinVin/citra_android#103]
I can't find the save files.

**Comment by Priyam005** [comment]
This should help-
storage/citra-emu/sdmc/ 
Nintendo 3DS/000000000000000 
00000000000000000/0000000000 
0000000000000000000000/title/ 
00040000
It might be a little different but you should be able to figure it out..

**Comment by Priyam005** [comment]
/sdcard/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/00040000/*yourtitle*/data/00000001/main
The 'main' file is the save file
