### ISSUE TITLE
Logfile

### ISSUE THREAD

**Issue by ApatheticEuphoria** [SachinVin/citra_android#106]
[   0.857425] Config <Error> citra_android/jni/config.cpp:ReadValues:169: Failed To parse init_time. Using 2000-01-01 00:00:01
[   0.876717] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   0.876750] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   0.904346] Core <Warning> core/core.cpp:Init:165: CPU JIT requested, but Dynarmic not available
[   0.906524] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:40: AudioCore::SelectSink given invalid sink_id 
[   0.907893] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:45: Error getting minimum latency
[   0.942748] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:307: ClCertA file missing
[   0.948798] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:568: GL_VERSION: OpenGL ES 3.0 V@145.0 AU@  (GIT@Iaf618d42e3)
[   0.948838] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:569: GL_VENDOR: Qualcomm
[   0.948848] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:570: GL_RENDERER: Adreno (TM) 308
[   0.977491] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:47: Error compiling fragment shader:
Fragment shader compilation failed.
WARNING: 0:4: extension 'GL_ANDROID_extension_pack_es31a' is not supported
ERROR: 0:7: ';' : Syntax error:  syntax error
ERROR: 1 compilation errors.  No code generated.

[   0.977549] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:48: Shader source code:
#version 300 es

#ifdef GL_ES
#extension GL_ANDROID_extension_pack_es31a : enable
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
precision highp samplerBuffer;
#else
precision mediump float;
precision mediump samplerBuffer;
#endif // GL_FRAGMENT_PRECISION_HIGH
#endif // GL_ES

uniform samplerBuffer tbo;
uniform vec2 tbo_size;
uniform vec4 viewport;

out vec4 color;

void main() {
    vec2 tbo_coord = (gl_FragCoord.xy - viewport.xy) * tbo_size / viewport.zw;
    int tbo_offset = int(tbo_coord.y) * int(tbo_size.x) + int(tbo_coord.x);
    color = texelFetch(tbo, tbo_offset).rabg;
}

[   0.977965] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadProgram:84: Error linking shader:
Invalid fragment shader. Link cannot proceed.

[   0.977992] Debug <Critical> video_core/renderer_opengl/gl_shader_util.cpp:operator():88: Assertion Failed!
Shader not linked

**Comment by SachinVin** [comment]
Your phone doesn't support GLES 3.2
