### ISSUE TITLE
When can Kirin processor play games normally?

### ISSUE THREAD

**Issue by CSF888888888** [SachinVin/citra_android#11]
When can Kirin processor play games normally?

**Comment by ricardojackson** [comment]
in my phone does not work is a samsung galaxy s9 figate your

**Comment by CSF888888888** [comment]
My phone doesn't work, it's Huawei P10.

**Comment by Cooldude245** [comment]
I cant say when it's going to be fixed since it's only one guy working on this so it could be a few months to a few years

**Comment by ricardojackson** [comment]
I hope it's soon that I'm looking forward to playing with my mobile to 3ds
games

**Comment by Paraskevidis** [comment]
Contact whoever is responsible for the GPU drivers and tell them to improve them.
If many people do that I'm sure they will listen us

**Comment by Cooldude245** [comment]
> Contact whoever is responsible for the GPU drivers and tell them to improve them.
> If many people do that I'm sure they will listen us

lets not do that, it'll just annoy whoever making them

**Comment by Paraskevidis** [comment]
Well then we can only sit and wait for a miracle to happen
