### ISSUE TITLE
my emulator crashes

### ISSUE THREAD

**Issue by HenriqueJoaoMd** [SachinVin/citra_android#113]
I have a moto G6 play, With Android 8.0, and every time I try to open majora's 3d masks, my emulator closes itself (I've already seen gameplay of people playing on YouTube), and I'm using citra0.5.1

**Comment by HenriqueJoaoMd** [comment]
Here is what It says on the log:

[ 179.999769] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[ 179.999808] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[ 180.050984] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: Secure1 KeyX missing
[ 180.051023] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:189: Secure2 KeyX missing
[ 180.051042] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:271: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[ 180.052059] Core <Warning> core/core.cpp:Init:165: CPU JIT requested, but Dynarmic not available
[ 180.054177] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:40: AudioCore::SelectSink given invalid sink_id 
[ 180.055695] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:45: Error getting minimum latency
[ 180.092921] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:307: ClCertA file missing

**Comment by SachinVin** [comment]
can you re-run the game and make sure there are more lines in the log (you might have to try it a couple of times)

**Comment by HenriqueJoaoMd** [comment]
I reinstalled the emulator, and tried to run the game five more times

That's what it said in the log:

[   1.010228] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   1.010278] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   1.063143] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: Secure1 KeyX missing
[   1.063185] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:189: Secure2 KeyX missing
[   1.063206] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:271: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   1.064171] Core <Warning> core/core.cpp:Init:165: CPU JIT requested, but Dynarmic not available
[   1.066154] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:40: AudioCore::SelectSink given invalid sink_id 
[   1.068722] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:45: Error getting minimum latency
[   1.106301] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:307: ClCertA file missing

**Comment by SachinVin** [comment]
do other games work? this seems like a moto specific issue like #59 and #89

**Comment by HenriqueJoaoMd** [comment]
I tried the same thing with the super Mario 3D land, it happened the same thing

I think the log is the same:

[   1.434165] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   1.434206] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   1.485605] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: Secure1 KeyX missing
[   1.485659] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:271: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   1.486882] Core <Warning> core/core.cpp:Init:165: CPU JIT requested, but Dynarmic not available
[   1.489053] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:40: AudioCore::SelectSink given invalid sink_id 
[   1.491052] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:45: Error getting minimum latency
[   1.533859] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:307: ClCertA file missing

**Comment by level5-fanboy** [comment]
@SachinVin In a way, you're correct. A number of mid-range Motorola phones (I can think of the Moto Z Play and Moto G5 off the top of my head) have arm64 processors, but use 32-bit stock ROMs. Seems that people don't really know that, however.
The only way someone with these phones can run Citra is by flashing a custom ROM with 64-bit support.

**Comment by HelloOO7** [comment]
You're right, Iooks lke Motorola is still using 32-bit even after the XDA outrage. From what I've seen, most 4GB+ RAM models are 64-bit (why would you have more than 4 on 32?) and the G5 Plus and Moto Z Play can be flashed with a custom rom to enable 64-bit operations. Non-plus G6s are out of luck, unfortunately. It's a shame, they aren't bad devices at all.
