### ISSUE TITLE
Snapdragon 845🔥 

### ISSUE THREAD

**Issue by EscanorXX** [SachinVin/citra_android#115]
I was thinking if there's any way to make it run smoother in the top devices that have Snapdragon 845 integrated. The most powerful performance chipset and latest for Android Devices. I can't believe that my laptop that only has like 2GB RAM and has some crap chipset (Dual Core or sum), plus it's a LENOVO... Runs Pokemon Sun X5 times better than I do in my POCOPHONE F1 (Snapdragon 845, Octa-Core, 6GB RAM) getting unbelievable FPS and it doesn't seem to get better when I disable the sound/music of the games.

I'll attach images soon. 

Sent from my POCO F1 using [FastHub]

**Comment by EscanorXX** [comment]
![CLICK HERE TO SEE THE PICTURES ](http://imgur.com/gallery/Zs1Gqhn)

**Comment by EscanorXX** [comment]
CLICK HERE TO SEE THE PICTURES 

[http://imgur.com/gallery/Zs1Gqhn] (url)

**Comment by EscanorXX** [comment]
http://imgur.com/gallery/Zs1Gqhn

**Comment by Guns29** [comment]
Ok first off you can not compare android platform with windows or mac platform they are different systems and it's more about optimizations not systems lmao just relax and wait for updates ok

**Comment by EscanorXX** [comment]
Alright👍🏾
