### ISSUE TITLE
Citra crashes!

### ISSUE THREAD

**Issue by xXJesucristoXx** [SachinVin/citra_android#116]
While I install the app it crash and while I try to start a game it crash too!
Please help me I want to play my favorites games😥

**Comment by Guns29** [comment]
This might have to do with the rom make sure your roms are not from venom there roms crashes the emu also make sure your phone is compatible with the emu

**Comment by bobbymc1985** [comment]
What game are you trying to play? What device are you using?

**Comment by HelloOO7** [comment]
Oh boy, here we go again, Citra will not work for the following reasons:

- Your CPU is 32-bit
- Your GPU is too weak; supports OpenGL ES only up to 2.0 and is from effin' 2008. Did you really expect to play anything on that?

@SachinVin I think the system requirements should be added to the contribution guidelines, with caps lock on preferrably, as there's way too many people with phones incapable of running candy crush asking if they can run dem pokeymanz on their 1 gigabyte CPU with 512 watts of ram and 2008 GPUs.

**Comment by xXJesucristoXx** [comment]
Well I have to wait like 2 years for compability between citra and ma phone

**Comment by HelloOO7** [comment]
Nah, you'll be waiting forever if you stay with your phone for that long. It's just too bad to ever be supported.

@SachinVin Can we close this?

**Comment by EscanorXX** [comment]
What is even b Blue studio G2 HD?!

**Comment by HelloOO7** [comment]
Apparently, [a phone.](https://www.gsmarena.com/blu_studio_g2_hd-8461.php) of a brand named BLU based in Miami. Even their """high-end""" phones have a Mediatek :smile: .

**Comment by EscanorXX** [comment]
@HelloOO7 Yo. I searched up in google and I'm in my tears. 😂😂😂😂. This phone can't and will not ever be able to run Citra. 💀😭

**Comment by bobbymc1985** [comment]
Best to get a device with snapdragon 845.  But I am very curious on how the shield tvs higher open gl 4.5 will affect it down the line

**Comment by xXJesucristoXx** [comment]
Naguebonah a s9 for citra i'll pass it's so expensive

**Comment by HelloOO7** [comment]
@YasunaMC Software renderer only, unless Samsung suddenly decided not to make shit drivers. Which means little to no difference from your S8.

@bobbymc1985 You're mixing apples with oranges here. The Shield has OpenGL 4.5, while citra_android uses OpenGL ES (as in Embedded Systems) 3.2. If you toyed around with SachinVin/citra and removed the hardware renderer, you could run it without graphics bugs and much faster. If you got a shield TV, I could try doing something about it (it's literally just resetting some files to official Citra's code). Feel free to open an issue on my fork if you have one and I could maybe start a new branch. If it actually worked, we'd still need to figure out how to switch between the renderers based on devices. I could do a setting for that in Java, but integrating it with cpp would be up to somebody else. I'm not too familiar with Android natives development.

@xXJesucristoXx Come on, this is an ISSUE TRACKER, not a chat. By the way, Ugandan Knuckles is a terrible meme (not to mention it's dead) and using xX Xx in names got old in like... 2013? Really, if you've got something relevant to say, ok, but this is just abuse of poor Github.

**Comment by xXJesucristoXx** [comment]
@Hello007 well I use this avatar 'cause i'm really bored to find a good photo and I use THIS username since 2009 in every aplication, game, app,etc

**Comment by HelloOO7** [comment]
@xXJesucristoXx Alright, fine (you don't need to have an avatar on Github btw, it auto-generates one for you), but can we please stop discussing things like "s9 expensive thus note 9 bad lmao". This issue is resolved. Please don't respond to this comment and let @SachinVin close it. Thank you.

**Comment by YasunaMC** [comment]
@HelloOO7 sorry to say but I use software render on my s8+ and got 15+ fps

**Comment by bobbymc1985** [comment]
I've had a shield tv for abt 6 months now. If the developer wants anything tested on it I Don not mind and report any findings I have if that is something that may want done in the future

**Comment by YasunaMC** [comment]
I hate people that says your device is bad for whatever I know why some people do that because they can only afford a Chinese phone or a apple fan boy

**Comment by xXJesucristoXx** [comment]
It's supose that this is an issues forum so if somebody presents problems the depelovers can TRY to solve them in this case an incompatibility problem, I have seen others ussers(not of Github) whit the same problem as me

**Comment by Guns29** [comment]
Ok first off citra does not support 32bit systems it supports phones that have a 
64-bit architecture your phone will never get citra to work with it sorry my advice is to get a newer phone sorry

**Comment by HelloOO7** [comment]
@YasunaMC Sorry if you misunderstood, I'm not saying your phone is bad, I'm saying that Samsung makes bad drivers (compared to Qualcomm or NVIDIA). Which you can easily prove by seeing how this performs on a SD845 which is pure power-wise weaker than the Exynos in S8.

@bobbymc1985 Tried to hack back SachinVin's code and it seems that it could work, I just need to find a way to make GL context on the shield.

@xXJesucristoXx But it's not possible to solve your problem, I told you that in my very first comment. Citra does not run on 32-bit even on PCs, are you seriously thinking it could on 32-bit Android? Wiťh 1GB of RAM? On a 2008, that's two thousands EIGHT, GPU? No.

This is getting out of hand. @bobbymc1985 if you want to do some testing on the shield, open an issue on HelloOO7/citra.

**Comment by Rohan100000** [comment]
Can my Galaxy J7 Prime G610F Run Pokemon X with this? It's crashing when i start game.

**Comment by HelloOO7** [comment]
Yes, your phone will be able tu run Citra (software renderer only probably). And no, it will not run Pokémon X. That game is only playable on a 3DS, it has heavy issues on PC too.

**Comment by EscanorXX** [comment]
@xXJesucristoXx You can be whatever you want whenever you keep in your mind that the correct requirements to run Citra are:

- Adreno 530
- 64Bit processor
- OpenGL 3.1+

Find a better Blue Studio phone.

**Comment by SachinVin** [comment]
Welp... gonna close this
