### ISSUE TITLE
when is going to see an update in citra that works more fuida games let's say more decent to play

### ISSUE THREAD

**Issue by Ricardojackson24** [SachinVin/citra_android#125]
Hello, a month ago and little of the last update of the application, citra wanted to ask sanchinVip when he will receive an update of the citra application for games and everything that works like on the computer, says 100 percent, because I'm waiting. to the berry games at 50 or 80 fps, I hope that you respadas for the samsung s9 thanks sanchinvip best regards

**Comment by Ricardojackson24** [comment]
in my samsung galaxy s9 I go very little fps I would like to play the games of dragon ball heroes I asked sanchinvip

**Comment by SachinVin** [comment]
No ETAs
