### ISSUE TITLE
Nova versão do citra Android 

### ISSUE THREAD

**Issue by davyson441** [SachinVin/citra_android#131]
Sashivin amigo gostaria de saber que dia vai lançar a nova versão  obg.

**Comment by YasunaMC** [comment]
english plz

**Comment by davyson441** [comment]
I would like to know what day an update will come out that does not give a problem opening a game. THX

**Comment by HelloOO7** [comment]
No ETAs. If you want an official statement, read: https://github.com/SachinVin/citra_android/issues/125#issuecomment-444356141

This is to be expected with open-source projects, think about it, the only emulator team ever giving ETAs is the Cemu team, which is heavily funded by Patreon and is closed-source. How would you even come up with an ETA of something people do in their free time?
