### ISSUE TITLE
Add a message when a game need 3DS data (external/not included)

### ISSUE THREAD

**Issue by EnergyCube** [SachinVin/citra_android#154]
Many games require **additional data**  to be able to run. Other game requires _at least 1 Mii_  but to run the Mii creator **once again requires additional data** . **I propose to add a message to inform the user that additional data is needed** (and _why not create an explanatory file_  (internal to the emulator or on github) to explain to the user how to fix that, sure, without ever giving a link (because it's illegal)). 

I wanted to do that because it's relatively easy, But I can not compile Citra ...

**Comment by HelloOO7** [comment]
It builds fine for me with the latest commits. You could open an issue with your compile log if you think it's not your machine's fault.
