### ISSUE TITLE
Error during sync

### ISSUE THREAD

**Issue by EnergyCube** [SachinVin/citra_android#155]
https://pastebin.com/uuGCexMN

**Comment by HelloOO7** [comment]
Dumb question, but you DID clone the repo recursively, didn't you? The fact that all the errors are externals-related is suspicious.

**Comment by EnergyCube** [comment]
@HelloOO7 hemmmmm... Yes :flushed:

**Comment by HelloOO7** [comment]
Well, try using the code from [this](https://drive.google.com/file/d/1F9jtyUc-tmcry9dGZG_AYfPDiXRoTSri/view?usp=sharing) archive (currently using that without problems). Just change the CMake paths etc. If it works, something went wrong while cloning yours, if it does not, you have a messed up build environment.

**Comment by EnergyCube** [comment]
@HelloOO7 Thanks I will test that

**Comment by EnergyCube** [comment]
I have this error now : Expected output file at C:\Users\Vincent\Desktop\AndroidProjects\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a\externals\cubeb\speex for target speex but there was none

**Comment by HelloOO7** [comment]
Is this the only error there? If yes, you should probably clean the build folders from my gradle setup. They are half empty because it's like 3 gigabytes with the compiled cache, so I cleared most of them for the archive. That would explain why it's looking for a file that is not there.

**Comment by EnergyCube** [comment]
How :/
I deleted the build folder and the error still here

**Comment by HelloOO7** [comment]
There's some more in .gradle I think (don't delete the whole dir tho, there's some important stuff too). Just get rid of everything that is not needed. Oh, you could also do "Sync with File System", then "Sync Gradle".

**Comment by SachinVin** [comment]
It's probably the weird cmake/Gradle bug, you can get it to work by
downgrading cmake to 3.11 or lower

**Comment by EnergyCube** [comment]
So,
Sync with File System
Sync Gradle
ERROR

Downgrade CMAKE to 3.11
Build command failed.
Error while executing process C:\Program with arguments {Files\CMake\bin\cmake.exe --build C:\Users\Vincent\Desktop\AndroidProjects\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a --target citra-room}
[0/1] Re-running CMake...
CMake Error: The source directory "" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
FAILED: build.ninja 
"C:\Program Files\CMake\bin\cmake.exe" -SC:\Users\Vincent\Desktop\AndroidProjects\citra -BC:\Users\Vincent\Desktop\AndroidProjects\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a
ninja: error: rebuilding 'build.ninja': subcommand failed

Note : ninja.exe is in C:\Program Files\CMake\bin\

**Comment by EnergyCube** [comment]
So 😥

**Comment by HelloOO7** [comment]
Well, something is seriously fuc*ed up. I've never encountered anything
like this with CMake (though I have never used ninja), and even on a
Windows host (8.1), everything worked right off the bat. The build system
does not tell us much about where the error happened (which line). I'd
suggest checking your build.ninja if there is anything that corresponds to
the build output. But I really don't know. The build.ninja files should be
the same for everyone. I'm on CMake 3.8.2 if that helps.

>

**Comment by EnergyCube** [comment]
Ohhhh God why I always have problems... I will try everything again ...
But if someone can do a tutorial on a clean Windows I take.

**Comment by EnergyCube** [comment]
Still have error : https://pastebin.com/mVeN5LDi
I will give up if it continues.

**Comment by HelloOO7** [comment]
Well, the line with the error in CMakeLists.txt clearly states that you need CMake 3.8 minimum. So if you're using 3.6, it obviously won't do anything.

Smh did you really NOT check what the line says?

**Comment by EnergyCube** [comment]
@HelloOO7 Android Studio force the old version...

**Comment by HelloOO7** [comment]
Well, delete it then. 3.8.2 is what works for me.
