### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by HansAngelo815** [SachinVin/citra_android#156]
Hello there...
i just want to ask whether there will be a new release soon on this project, (not rushing you) just wondering if there will be a future update in optimizing and polishing this emulator...

**Comment by EnergyCube** [comment]
Assuming the application is not official. So there is a very small community. Anyone wishing to help develop the application or optimize it is welcome. To develop this application is to spend time ... free time. The application is developing slowly. In any case, ask if a new version will come out will not change anything.

**Comment by HelloOO7** [comment]
Looks like nobody here wants to react to this, so I'll do it, just 'cause you asked so politely.

No ETAs. That's the rule of most open-source projects. SachinVin stated this many times before.

But yes, there MAY be updates. Depends on if anyone wants to code an ARM recompiler in the case of optimizations. And no sane person I know would want to do that just by themselves. Considering the 3DS is already widely REd, it's much easier now than it was five years ago when Citra started, but nevertheless still time consuming.

That is, there are plans for an official Android port. Nobody knows when it's going live (not even the creators, seriously, there's nothing like NDAs in open-source, it's just that noone's working full-time), but don't expect it to magically get much better than this fork just because it's official.

**Comment by HansAngelo815** [comment]
Thank you for the reply @HelloOO7
 
If there is any thing that I can contribute to this project lets say... being a beta tester on citra android please let me know and I will gladly help in describing bugs and fixes on the emulator

**Comment by HelloOO7** [comment]
Umm, considering this is nothing more than a really unstable beta, everyone who's using it is already a beta tester. There's no secret testing-only code, everything is pushed to this repo once it's confirmed working and it's coded properly.

**Comment by HansAngelo815** [comment]
@HelloOO7
is there a possibility if @SachinVin works with the Citra dev team in making this emulator?
(just wondering)

**Comment by EnergyCube** [comment]
@HansAngelo815 
From the Citra FAQ : 

Are you planning to make an Android version?

No, not at the moment.

**Comment by HelloOO7** [comment]
Well, there ARE plans. If you don't believe BreadFish64's numerous statements and the app base in `citra-emu/src/android`, then idk.

**Comment by HansAngelo815** [comment]
Hi @HelloOO7 
that when i was looking at the Google playstore, i saw the emulator app there uploaded by @EnergyCube.... is this the same emulator from this thread?

**Comment by HelloOO7** [comment]
Yep, he just took SachinVin's work and published it there. The license allows that, so it's probably fine. But it's not a good idea, people review bomb any emulator on Play if it does not run full speed on a "powerful Xiaomi phone".

**Comment by HansAngelo815** [comment]
Yeah @HelloOO7 i get that a lot....
I also noticed that @GameCube seems to work with @SachinVin in this project....
is this true?🤔

**Comment by EnergyCube** [comment]
@HelloOO7 That's why I publish the emulator in BETA x')
 They can't rate the application, they only can send mail for request help or signal bugs.
(I put the application on the PlayStore to facilitate the installation and to track bugs)

**Comment by HelloOO7** [comment]
@HansAngelo815 I don't think so, he does not even have his own branch of it. AFAIK there's only SachinVin working in it and occasionally, someone else pushes a few commits.

@EnergyCube Well, you have my condolences. The average google-play-emulator-downloading-person mostly does not know anything about how development of open-source emulators actually works. Hope you don't get flooded by third world country people's emails asking for unreal features and optimizations. Youtube comments and sometimes even this issue tracker host a lot of people who just want to play games they don't even own on their phones, then it does not work, then they complain without actually reading the system requirements.

**Comment by HansAngelo815** [comment]
@HelloOO7 has a point...
it's better to first look the emulator up on github for updates, then post on the Google Playstore.

@EnergyCube its also nice that you uploaded on google play but just be aware of comments of other people okay❤️

**Comment by ghost** [comment]
Hey there
I just searched up citra on the play store and the one uploaded by @energycube came first but after scrolling down a bit another one also came (I didn't say it was citra) but it was a 3ds emulator (https://play.google.com/store/apps/details?id=com.stablemobile.stable3d) and it looks fishy so would some actually test it and see if it has any potential??

**Comment by EnergyCube** [comment]
@Priyam005 All fake.... Probably Trojan... They use the possibility to release the application in BETA to not have negative feedback and to get others to download their bullsh*t.

**Comment by EnergyCube** [comment]
@Priyam005 All fake.... Probably Trojan... They use the possibility to release the application in BETA to not have negative feedback and to get others to download their bullsh*t.

**Comment by HansAngelo815** [comment]
Fake bro @Priyam005
dont be fooled by some apps being randomly posted.....
be careful🤔🤔
