### ISSUE TITLE
Inverted Colors

### ISSUE THREAD

**Issue by HansAngelo815** [SachinVin/citra_android#157]
Hey there guys it's me again....
Just tried the emulator and played pokemon omega ruby, and saw some weird glitched colors on the screen while playing...
the game runs tho' but downside is the color emulation problems

**Comment by HelloOO7** [comment]
That's a known issue that was discussed here many times, not to mention it's been acknowledged from the start in the README (as in "read me", that means you're supposed to read it). Ugh, we really need those issue and contribution guidelines.

**Comment by WesleyVanNeck** [comment]
@HelloOO7  true you guys need it

**Comment by HansAngelo815** [comment]
Haha sorry @HelloOO7
my bad😁😁
