### ISSUE TITLE
Crash when opening a game.

### ISSUE THREAD

**Issue by matcool** [SachinVin/citra_android#16]
Upon trying to open a game (I've tested Super Mario 3D Land and Alien Chaos 3D) the app due to the rom not being decrypted (which in my opinion should just open a error message instead of crashing the whole app).

 - Device: Motorola g5
 - OS: Android 8.1
 - CPU: Qualcomm Snapdragon 430
 - GPU: Qualcomm Adreno 505 (OpenGL ES Version 3.2)
 - Version 0.4.1 alpha

```
[   1.732354] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   1.732399] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   1.793024] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:179: ExHeader Program ID mismatch: the ROM is probably encrypted.
[   1.793071] Core <Critical> core/core.cpp:Load:95: Failed to determine system mode (Error 8)!
[   1.793292] Frontend <Critical> citra_android/jni/native.cpp:RunCitra:124: The game that you are trying to load must be decrypted before being used with Citra. 

 For more information on dumping and decrypting games, please refer to: https://citra-emu.org/wiki/dumping-game-cartridges/
```
PS: the decrypting on the wiki seems to require an actual 3DS, is there any way to decrypt only using your pc?

**Comment by Blight-kun** [comment]
yes i have the software, it greets with the title "Noob Friendly 3DS, SCU to CIA Converter 4.1" not mine tho but can convert cia to 3ds

**Comment by matcool** [comment]
Update: I got a decrypted rom (it even has the game icon on the library) but im still crashing upon opening.
Heres the log:
```
[   4.341914] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   4.342385] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   4.399060] Core <Warning> core/core.cpp:Init:162: CPU JIT requested, but Dynarmic not available
[   4.399968] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:39: AudioCore::SelectSink given invalid sink_id 
[   4.428121] Service.FS <Error> core/file_sys/savedata_archive.cpp:OpenFile:67: Non-existing file ./sdcard/citra-emu/nand/data/00000000000000000000000000000000/sysdata/00010017/00000000/config can't be open without mode create.
[   4.428280] Service.FS <Error> core/file_sys/savedata_archive.cpp:DeleteFile:109: File not found ./sdcard/citra-emu/nand/data/00000000000000000000000000000000/sysdata/00010017/00000000/config
```

**Comment by SachinVin** [comment]
did you dump your system files ?
If not follow guide [here](https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/)

**Comment by InazumaIulius** [comment]
Why Is your Adreno 505 supporting OPEN GL ES 3.2? I have a Snapdragon 616 and Adreno 505 with only OPEN GL ES 3.1? :( 
Is there any update oppertunity?

**Comment by matcool** [comment]
After I added the shared font on the `sysdata` folder and the other data onto the `nand` folder I now get this error:
```
[ 0.023215] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[ 0.023249] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[ 0.074911] Core <Warning> core/core.cpp:Init:162: CPU JIT requested, but Dynarmic not available
[ 0.075829] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:39: AudioCore::SelectSink given invalid sink_id 
```

**Comment by Nishant765** [comment]
Hey can you guys tell me where to paste the user folder on Android? I know how to do it on the PC.

**Comment by Priyam005** [comment]
@Nishant765 You have to copy the folder(s) inside of the user folder and paste them in the citra-emu folder in the internal storage of your phone (if you have played any game on citra for even once then that folder should be there)

**Comment by Nishant765** [comment]
I know that bro. But can you tell me the step by step directions like which
folder and subfolder to paste it on? Thank you so much.

**Comment by Priyam005** [comment]
Am really glad to hear you fixed it ;)

**Comment by KeiKun67** [comment]
I can't play Harvest Moon An New Beginning or Story Of Season, When i run the rom the app close.....

**Comment by Priyam005** [comment]
@KeiKun67 please tell me the specifications of your phone

**Comment by Priyam005** [comment]
@KieKun67 it looks like your phones does not support citra for confirmation I would more detailed specifications like the architecture and opengl version

**Comment by KeiKun67** [comment]
I cant specifically explain it but does this help https://www.google.com/url?sa=t&source=web&rct=j&url=https://gadgets.ndtv.com/xiaomi-redmi-note-5a-4333&ved=2ahUKEwiz7ouByP7dAhXTFogKHUX2DcYQFjAAegQIBBAB&usg=AOvVaw1K7BB0CXNDgfaZ-had6rwm

**Comment by nishant** [comment]
@Priyam005 please mention the correct Nishant @Nishant765.i have been getting notifications from this thread.

**Comment by matcool** [comment]
closed because way too many off topic comments (make your own issue please)

**Comment by VhykTR** [comment]
Hi
