### ISSUE TITLE
Can Samsung J7 Pro run citra and play Pokemon Ultra Moon?

### ISSUE THREAD

**Issue by Haganail** [SachinVin/citra_android#162]
Title says it all XD (Just asking)

**Comment by ghost** [comment]
I'm not 100% sure about this, as I don't own the device, but a quick Google search reveals that although the CPU is 64-bit, the OS is apparently 32-bit (64-bit is one of the requirements), so no. Your best course of action is to rip your game from your 3ds and try the emulator on your phone. Even if it works, it's in a very early state, so don't expect full speed or high compatibility.

**Comment by Haganail** [comment]
Will it be in full speed in the next update?

**Comment by boytoy91** [comment]
He'll no
