### ISSUE TITLE
Start from scratch

### ISSUE THREAD

**Issue by ghost** [SachinVin/citra_android#164]
Well I am thankful to all of you, guys for making this emulator this far to this stage

But I still wanted to suggest something (well sorry, I have no right to force you all) I think that the Citra emulator has many bugs and problems because of the unused strings from the **Dolphin Emulator**

I think starting from scratch will make us help to solve bugs and make the app less conjusted as it is now.

**Comment by ghost** [comment]
It's just a suggestion

Don't feel forced by it...

**Comment by boytoy91** [comment]
Do it your self then

**Comment by ghost** [comment]
I am no developer
That's why I politely suggested them what I feel

**Comment by boytoy91** [comment]
Well you could ask B0b D0E of the Citra team they won't do it because of the issues with the api and many other issues like open gles etc

**Comment by WesleyVanNeck** [comment]
same here do it your self if you complain about this code like its exmental so it wouldnt work like a flash duhh

**Comment by SachinVin** [comment]
Actually the citra team IS working on building the android version from scratch.
I mostly didnt do it because it because it would've taken a massive amount of work just to get something decent enough to be usable. Granted some of dolphin's code is unusable but that is mostly just because dolphin is two emulators in one one package and has to deal with switching between them.

**Comment by boytoy91** [comment]
Agreed.. Will there be a update in the future

**Comment by SachinVin** [comment]
In the near future? probably not, I'm kinda busy at the moment and possibly
for the next couple of months, so, no

**Comment by boytoy91** [comment]
Well 10 fps on Pokémon ultra sun and moon running huawei p20 pro

**Comment by ghost** [comment]
> Actually the citra team IS working on building the android version from scratch.
> I mostly didnt do it because it because it would've taken a massive amount of work just to get something decent enough to be usable. Granted some of dolphin's code is unusable but that is mostly just because dolphin is two emulators in one one package and has to deal with switching between them.

You mean the original citra team that built the Citra 3ds emulator for Windows.

And when can we expect that update?

Will it be introduced in the next release??
