### ISSUE TITLE
Can it play Wii U games like Zelda BOTW?

### ISSUE THREAD

**Issue by anubhavuniyal** [SachinVin/citra_android#168]

**Comment by WesleyVanNeck** [comment]
no ofc not

**Comment by WesleyVanNeck** [comment]
buy a pc you can make one for 120 euros and you got better perf

**Comment by anubhavuniyal** [comment]
Well, can it support vulkan in the near future, for better perf

**Comment by EnergyCube** [comment]
However, you can play the best Zelda game : Zelda OoT :3

**Comment by anubhavuniyal** [comment]
True that!

**Comment by Cooldude245** [comment]
Yes you can totally play a wii u game like botw on a 3ds emulator
