### ISSUE TITLE
How to save a Pokemon game in emulator

### ISSUE THREAD

**Issue by ghost** [SachinVin/citra_android#170]
I played a game but I can't save a game

**Comment by ghost** [comment]
You will need to save the game from within the emulator..in Pokemon games you can save by tapping the notebook like icon on the second screen

**Comment by ghost** [comment]
Where is second screen

**Comment by HelloOO7** [comment]
Lmao.

It's Nintendo 3DS, as for Three-dimensions dual-screen. The second screen is the bottom one of the two.
