### ISSUE TITLE
Games don't even show up

### ISSUE THREAD

**Issue by NoelleTGS** [SachinVin/citra_android#178]
I feel like this might be a problem on my part but my games doesn't even show in the list. I've tried different versions, I've tried putting it in different folders. Is this supposed to run .cia files?

**Comment by mrkuyaJv** [comment]
Maybe it doesn't support your device.

**Comment by HelloOO7** [comment]
No, only desktop Citra supports CIA installation. I have no idea as to why you opted for dumping as CIA but you should always dump as .3DS if you plan on emulating. Open GM9, go to the gamecart directory and copy either the trimmed or untrimmed 3DS file to your SD card. Citra should then recognize it right away and maybe even run it to varying degrees of playability.

**Comment by BelieveMeImAnArtist** [comment]
try dumping decripted 3ds games  , mine work with those

**Comment by DyG121** [comment]
I also had such problem. In my case changing file name helped. I'm not sure if it was too long, or it had some signs that it couldn't recognize, but file name was the thing.

**Comment by Ae3NerdGod** [comment]
Afaik, this only runs decrypted 3ds files. 

Perhaps if you install the cias on desktop citra and copy your user folder? But the better option imo is just decrypt it into a 3ds file.  (an easy Google search will give you a guide).
