### ISSUE TITLE
Vulkan?

### ISSUE THREAD

**Issue by Paraskevidis** [SachinVin/citra_android#18]
Is there Vulkan support right now?
Maybe phones without that missing extension that SachinVin mentioned could run in non snapdragon devices with Vulkan?

Like in Dolphin I get a message about ext buffer missing when I use opengl mode but I don't have it when I use Vulkan and my speed is better in Vulkan btw!

Im just asking without knowing too much about this whole stuff so I could be way wrong

**Comment by SachinVin** [comment]
Whenever official citra supports it

**Comment by Emulatorer** [comment]
@SachinVin Hi Im new here can I ask if you already contacted the Citra Team? 
![screenshot_2018-10-08-10-56-08](https://user-images.githubusercontent.com/37603562/46590823-f98d4600-caa5-11e8-845f-07378c8583b1.png)
Because I ask theme too 😅

*sorry 4 my bad englsh
