### ISSUE TITLE
Supported file extensions!

### ISSUE THREAD

**Issue by ghost** [SachinVin/citra_android#183]
What file extensions are supported by this emulator???

**Comment by WesleyVanNeck** [comment]
.3ds

**Comment by ghost** [comment]
Does it support (.**cci**) or (.**cxi**)???
And any other??

**Comment by WesleyVanNeck** [comment]
No

**Comment by HelloOO7** [comment]
Now that is not at all true. Citra does support many 3DS container types and most of them are handled in the android version. See `app/src/main/java/org/citra/citra_android/model/GameDatabase.java`:
```

Set<String> allowedExtensions = new HashSet<String>(Arrays.asList(
".3ds", ".3ds", ".3dsx", ".elf", ".axf", ".cci", ".cxi", ".app"));
```

Whether they load, now that is a different story (I haven't tried, all my dumps are .3DS). With that being said, it's not hard to convert between all these containers and redumping the game is always an option.

Edit: Forgot to mention that, but why exactly is this an "issue"? Should you not be able to find the info I mentioned above yourself? This is highly experimental (and development is suspended in this repo AFAIK), the only people that should be using the emulator right now are developers with intentions to contribute (or people with SD 855s), and those would know how to do a two minute search through the source.
