### ISSUE TITLE
Hey... The App has ben removed from the PlayStore

### ISSUE THREAD

**Issue by EnergyCube** [SachinVin/citra_android#185]
Hello, for some time the application has been removed from PlayStore for violation of the property rules.
Normally I have the right to put the application on the PlayStore since I'm only sharing it ... But it would seem that people at Google is not the same opinion ...

So I just ask @SachinVin if he wants me to put the application on the PlayStore.
If so, just say you give me the agreement, I will share the bug ticket with Google and the application will be unlocked (I think).

**Comment by bobbymc1985** [comment]
One thing I did notice. The playstore version was able to get pokemon x working till you start play then became a black screen. This version Very needs updated

**Comment by BreadFish64** [comment]
Hello @EnergyCube I'm from the Citra team. We would appreciate it if you didn't use our name and logo. It would ease a lot of headache when users ask us for help and we can't do anything about it. And there will be less confusion when we eventually release our own app.

**Comment by EnergyCube** [comment]
> Hello @EnergyCube I'm from the Citra team. We would appreciate it if you didn't use our name and logo. It would ease a lot of headache when users ask us for help and we can't do anything about it. And there will be less confusion when we eventually release our own app.

Heeeee..
Yeah okay...

**Comment by Ae3NerdGod** [comment]
Its still using dolphin frontend code isn't it? That's probably the "violation of property"

Just give the developer (s) some time. According to xda, they're working with the developers of citra to make this project more official

**Comment by BreadFish64** [comment]
@Ae3NerdGod it's perfectly fine to use dolphins frontend code as long as the source is freely available

**Comment by EnergyCube** [comment]
@Ae3NerdGod The violation is the Name and the Icon of the application...
But no matter. @BreadFish64 seems to say that people will complain about the community of Citra (official) while they can not do anything.I prefer to leave things that way. 

Google is horrible... They allow fake emulators (ads/spy) and the only one that work they remove it... 


_Sent from my OnePlus 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by EnergyCube** [comment]
**Issues Clean Up**

_(a long time ago, just for archival purposes)_
Google had given me back the rights to the app due to a licensing error, but following @BreadFish64's request, I still permanently removed the app from the PlayStore, which was later [replaced](https://play.google.com/store/apps/details?id=org.citra.citra_emu) by the one of the official citra team.
