### ISSUE TITLE
This emulator does work on Xiaomi mi4s

### ISSUE THREAD

**Issue by AlphysKirisame** [SachinVin/citra_android#20]
is very impossible i test in Xiaomi Mi 4s and i play rom Animal Crossing:new leaf i open this rom 15 minute screen is black only controller 3ds and fps is work and frametime : 13.8966ms and speed : 100% but fps is 0,0.i Understand because the emulator is still pre-released,but I need a solution. okay that's all thank you

Spec
Ram:3gb
Processor:Qualcomm Snapdragon 808 
Gpu renderer:Adreno (TM) 418

**Comment by SachinVin** [comment]
did you dump your system files ?
If not follow guide [here](https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/)

**Comment by AlphysKirisame** [comment]
Ok i got it thx to solve
