### ISSUE TITLE
Blank display

### ISSUE THREAD

**Issue by AlvinZp** [SachinVin/citra_android#22]
When I open the Animal Crossing New Leaf and the Pokémon Ultra Sun it just show blank with FPS 0.00 but the ms and speed showing good?Is this game not support?
IMAGE:
https://imgur.com/a/qhaPKsm

**Comment by SachinVin** [comment]
did you dump your system files and/or shared fonts?
If not follow guide [here](https://citra-emu.org/wiki/dumping-system-archives-and-the-shared-fonts-from-a-3ds-console/)

**Comment by wesleyvanneck** [comment]
Got it working
