### ISSUE TITLE
Citra Android with Exynos CPU e.g Galaxy S10 very slow 

### ISSUE THREAD

**Issue by ghost** [SachinVin/citra_android#225]
Hi I loaded this citra 3DS emulator for Android

https://github.com/weihuoya/citra/releases
https://github.com/SachinVin/citra_android/releases

But on the Samsung Galaxy S10 (Exynos 9820 CPU) with Android 9 is very slow. The FPS are extremely low and the sound is not synchronous. I tested New Super Mario Bros. 2 3DS rom (decrypted).

A friend of mine uses a OnePlus 7 Pro (Snapdragon 855 CPU) and here it runs very smoothly. No problems at all.

It seems that the exynos cpu doesn't work properly, because I still have an old galaxy s6 (Samsung Exynos 7420) and the same problem here.

No problems with Qualcomm Snapdragon CPU.

**Comment by ghost** [comment]
@weihuoya

maybe the developer can say something?

because I also tested it and it doesn't work for me either.

**Comment by sahil03032001** [comment]
Tekken 3d prime nhi chal rha character name ke baad band ho jata hai
