### ISSUE TITLE
Citra crashes when opening pokemon sun and x

### ISSUE THREAD

**Issue by mubashir343** [SachinVin/citra_android#226]
I have a lenovo s90
 2GB ram
OS version 5.0.2
When I Open the game it blacks out and the emulator closes

**Comment by mubashir343** [comment]
Please help

**Comment by SachinVin** [comment]
Your phone is not supported

**Comment by mubashir343** [comment]
What is the minimum device requirement

**Comment by mubashir343** [comment]
Will it be optimized for my phone in future

**Comment by SachinVin** [comment]
No it will not be optimized
Min specs -
64 bit processor and OS
Gpu with gles 3.2 support

**Comment by ghost** [comment]
My device has 3 gb ram
64 bit processor
Gpu of 3.2
Than also it crashes

**Comment by SachinVin** [comment]
You should not be using this.

**Comment by michaelphagen** [comment]
Use https://github.com/weihuoya/citra/releases or https://play.google.com/store/apps/details?id=org.citra.citra_emu instead
