### ISSUE TITLE
Crashing when selecting from folder.

### ISSUE THREAD

**Issue by delurfangs** [SachinVin/citra_android#23]
I am on a Qualcomm note 8 and when selecting my rom folder the app force closes and continues to force close until app data is cleared.

**Comment by delurfangs** [comment]
Figured it out. I copied my encrypted roms instead of of the un-encrypted once I copied from the correct folder they worked. But some sort of error handling rather than a hard crash would be nice.

**Comment by SachinVin** [comment]
@delurfangs you're right, this is still in alpha stages, i was thinking of doing it when most of the app wqas ready.
So, if your issue is fixed can I close this?

**Comment by mrjerbaks** [comment]
Same Issue for my phone Oneplus one !

CPU : Qualcomm® Snapdragon™ 801 processor with 2.5GHz Quad-core CPUs
3GB RAM
64 Gb Storage 
i wish this helps
 and thanks for creating the app! im here to support!
