### ISSUE TITLE
Mali Gpu

### ISSUE THREAD

**Issue by AlvinZp** [SachinVin/citra_android#24]
Will it support for Mali GPU soon?Hope it can because all the requirements already check but not Mali.
My phone is Oppo A83 with Mali-G71 MP2
Here a log file if needed:
https://drive.google.com/a/yes.my/file/d/1s50MjZ2MVoWFybvg66lPCHpxWLywy-cY/view?usp=drivesdk

**Comment by SachinVin** [comment]
I can't say how soon

**Comment by wesleyvanneck** [comment]
the thing to get it working to fix the black screen issue use the user file of pc citra thing or 3ds
