### ISSUE TITLE
Build instructions? Both gradlew assemble and Android Studio give error configuring

### ISSUE THREAD

**Issue by zpoo32** [SachinVin/citra_android#27]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelDebug'.
> com.android.ide.common.process.ProcessException: Error configuring

I have gotten both SachVin/citra_android and SachVin/citra_android cloned in the same folder, with their own respective folders in it, but this gives an error. Am I missing something? The build instructions are unclear.

Please help, and thanks in advance!

**Comment by zpoo32** [comment]
Full log:

gradlew assemble

> Configure project :app
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html
Support for CMake 3.7 and higher is a preview feature. To report a bug, see https://developer.android.com/studio/report-bugs.html

> Task :app:generateJsonModelDebug FAILED
External native generate JSON debug: starting JSON generation
External native generate JSON debug: using platform version 21 for ABI X86_64 and min SDK version 21
External native generate JSON debug: rebuilding JSON C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\x86_64\android_gradle_build.json due to:
External native generate JSON debug: - expected json C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\x86_64\android_gradle_build.json file is not present, will remove stale json folder
External native generate JSON debug: - missing previous command file C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\x86_64\cmake_build_command.txt, will remove stale json folder
External native generate JSON debug: removing stale contents from 'C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\x86_64'
External native generate JSON debug: created folder 'C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\x86_64'
External native generate JSON debug: executing cmake Executable : C:\Users\Ariok\Downloads\Git\citra_android\Sdk\cmake\3.6.4111459\bin\cmake.exe
arguments :
-HC:\Users\Ariok\Downloads\Git\citra
-BC:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\x86_64
-DANDROID_ABI=x86_64
-DANDROID_PLATFORM=android-21
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Ariok\Downloads\Git\citra_android\app\build\intermediates\cmake\debug\obj\x86_64
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle
-DCMAKE_SYSTEM_NAME=Android
-DCMAKE_ANDROID_ARCH_ABI=x86_64
-DCMAKE_SYSTEM_VERSION=21
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-DCMAKE_ANDROID_NDK=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle
-DCMAKE_TOOLCHAIN_FILE=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake
-G Ninja
-DANDROID_STL=c++_static
-DENABLE_QT=0
-DENABLE_SDL2=0
-DENABLE_WEB_SERVICE=0
-DANDROID_ARM_NEON=true
-DENABLE_CUBEB=0
jvmArgs :




[== "CMake Server" ==[

{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":2}],"type":"hello"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "handshake",
  "cookie": "gradle-cmake-cookie",
  "protocolVersion": {
    "isExperimental": true,
    "major": 1,
    "minor": 2
  },
  "sourceDirectory": "C:/Users/Ariok/Downloads/Git/citra",
  "buildDirectory": "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/x86_64",
  "generator": "Ninja"
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"gradle-cmake-cookie","inReplyTo":"handshake","type":"reply"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "configure",
  "cacheArguments": [
    "",
    "-DANDROID_ABI\u003dx86_64",
    "-DANDROID_PLATFORM\u003dandroid-21",
    "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\app\\build\\intermediates\\cmake\\debug\\obj\\x86_64",
    "-DCMAKE_BUILD_TYPE\u003dDebug",
    "-DANDROID_NDK\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle",
    "-DCMAKE_SYSTEM_NAME\u003dAndroid",
    "-DCMAKE_ANDROID_ARCH_ABI\u003dx86_64",
    "-DCMAKE_SYSTEM_VERSION\u003d21",
    "-DCMAKE_EXPORT_COMPILE_COMMANDS\u003dON",
    "-DCMAKE_ANDROID_NDK\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle",
    "-DCMAKE_TOOLCHAIN_FILE\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle\\build\\cmake\\android.toolchain.cmake",
    "-G Ninja",
    "-DANDROID_STL\u003dc++_static",
    "-DENABLE_QT\u003d0",
    "-DENABLE_SDL2\u003d0",
    "-DENABLE_WEB_SERVICE\u003d0",
    "-DANDROID_ARM_NEON\u003dtrue",
    "-DENABLE_CUBEB\u003d0"
  ]
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"CMake Error: CMake was unable to find a build program corresponding to \"Ninja\".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.","title":"Error","type":"message"}

]== "CMake Server" ==]

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.


[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","progressCurrent":1000,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"Configuring incomplete, errors occurred!\nSee also \"C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeOutput.log\".","type":"message"}

]== "CMake Server" ==]

Configuring incomplete, errors occurred!
See also "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeOutput.log".
Configuring incomplete, errors occurred!
See also "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/x86_64/CMakeFiles/CMakeOutput.log".


[== "CMake Server" ==[

{"cookie":"","errorMessage":"Configuration failed.","inReplyTo":"configure","type":"error"}

]== "CMake Server" ==]

Configuration failed.
External native generate JSON debug: using platform version 21 for ABI ARMEABI_V7A and min SDK version 21
External native generate JSON debug: rebuilding JSON C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\armeabi-v7a\android_gradle_build.json due to:
External native generate JSON debug: - expected json C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\armeabi-v7a\android_gradle_build.json file is not present, will remove stale json folder
External native generate JSON debug: - missing previous command file C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\armeabi-v7a\cmake_build_command.txt, will remove stale json folder
External native generate JSON debug: removing stale contents from 'C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\armeabi-v7a'
External native generate JSON debug: created folder 'C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\armeabi-v7a'
External native generate JSON debug: executing cmake Executable : C:\Users\Ariok\Downloads\Git\citra_android\Sdk\cmake\3.6.4111459\bin\cmake.exe
arguments :
-HC:\Users\Ariok\Downloads\Git\citra
-BC:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\armeabi-v7a
-DANDROID_ABI=armeabi-v7a
-DANDROID_PLATFORM=android-21
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Ariok\Downloads\Git\citra_android\app\build\intermediates\cmake\debug\obj\armeabi-v7a
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle
-DCMAKE_SYSTEM_NAME=Android
-DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a
-DCMAKE_SYSTEM_VERSION=21
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-DCMAKE_ANDROID_NDK=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle
-DCMAKE_TOOLCHAIN_FILE=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake
-G Ninja
-DANDROID_STL=c++_static
-DENABLE_QT=0
-DENABLE_SDL2=0
-DENABLE_WEB_SERVICE=0
-DANDROID_ARM_NEON=true
-DENABLE_CUBEB=0
jvmArgs :




[== "CMake Server" ==[

{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":2}],"type":"hello"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "handshake",
  "cookie": "gradle-cmake-cookie",
  "protocolVersion": {
    "isExperimental": true,
    "major": 1,
    "minor": 2
  },
  "sourceDirectory": "C:/Users/Ariok/Downloads/Git/citra",
  "buildDirectory": "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/armeabi-v7a",
  "generator": "Ninja"
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"gradle-cmake-cookie","inReplyTo":"handshake","type":"reply"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "configure",
  "cacheArguments": [
    "",
    "-DANDROID_ABI\u003darmeabi-v7a",
    "-DANDROID_PLATFORM\u003dandroid-21",
    "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\app\\build\\intermediates\\cmake\\debug\\obj\\armeabi-v7a",
    "-DCMAKE_BUILD_TYPE\u003dDebug",
    "-DANDROID_NDK\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle",
    "-DCMAKE_SYSTEM_NAME\u003dAndroid",
    "-DCMAKE_ANDROID_ARCH_ABI\u003darmeabi-v7a",
    "-DCMAKE_SYSTEM_VERSION\u003d21",
    "-DCMAKE_EXPORT_COMPILE_COMMANDS\u003dON",
    "-DCMAKE_ANDROID_NDK\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle",
    "-DCMAKE_TOOLCHAIN_FILE\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle\\build\\cmake\\android.toolchain.cmake",
    "-G Ninja",
    "-DANDROID_STL\u003dc++_static",
    "-DENABLE_QT\u003d0",
    "-DENABLE_SDL2\u003d0",
    "-DENABLE_WEB_SERVICE\u003d0",
    "-DANDROID_ARM_NEON\u003dtrue",
    "-DENABLE_CUBEB\u003d0"
  ]
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"CMake Error: CMake was unable to find a build program corresponding to \"Ninja\".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.","title":"Error","type":"message"}

]== "CMake Server" ==]

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.


[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","progressCurrent":1000,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"Configuring incomplete, errors occurred!\nSee also \"C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log\".","type":"message"}

]== "CMake Server" ==]

Configuring incomplete, errors occurred!
See also "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
Configuring incomplete, errors occurred!
See also "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".


[== "CMake Server" ==[

{"cookie":"","errorMessage":"Configuration failed.","inReplyTo":"configure","type":"error"}

]== "CMake Server" ==]

Configuration failed.
External native generate JSON debug: using platform version 21 for ABI ARM64_V8A and min SDK version 21
External native generate JSON debug: rebuilding JSON C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a\android_gradle_build.json due to:
External native generate JSON debug: - expected json C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a\android_gradle_build.json file is not present, will remove stale json folder
External native generate JSON debug: - missing previous command file C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a\cmake_build_command.txt, will remove stale json folder
External native generate JSON debug: removing stale contents from 'C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a'
External native generate JSON debug: created folder 'C:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a'
External native generate JSON debug: executing cmake Executable : C:\Users\Ariok\Downloads\Git\citra_android\Sdk\cmake\3.6.4111459\bin\cmake.exe
arguments :
-HC:\Users\Ariok\Downloads\Git\citra
-BC:\Users\Ariok\Downloads\Git\citra_android\app\.externalNativeBuild\cmake\debug\arm64-v8a
-DANDROID_ABI=arm64-v8a
-DANDROID_PLATFORM=android-21
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Ariok\Downloads\Git\citra_android\app\build\intermediates\cmake\debug\obj\arm64-v8a
-DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle
-DCMAKE_SYSTEM_NAME=Android
-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a
-DCMAKE_SYSTEM_VERSION=21
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
-DCMAKE_ANDROID_NDK=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle
-DCMAKE_TOOLCHAIN_FILE=C:\Users\Ariok\Downloads\Git\citra_android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake
-G Ninja
-DANDROID_STL=c++_static
-DENABLE_QT=0
-DENABLE_SDL2=0
-DENABLE_WEB_SERVICE=0
-DANDROID_ARM_NEON=true
-DENABLE_CUBEB=0
jvmArgs :




[== "CMake Server" ==[

{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":2}],"type":"hello"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "handshake",
  "cookie": "gradle-cmake-cookie",
  "protocolVersion": {
    "isExperimental": true,
    "major": 1,
    "minor": 2
  },
  "sourceDirectory": "C:/Users/Ariok/Downloads/Git/citra",
  "buildDirectory": "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/arm64-v8a",
  "generator": "Ninja"
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"gradle-cmake-cookie","inReplyTo":"handshake","type":"reply"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{
  "type": "configure",
  "cacheArguments": [
    "",
    "-DANDROID_ABI\u003darm64-v8a",
    "-DANDROID_PLATFORM\u003dandroid-21",
    "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\app\\build\\intermediates\\cmake\\debug\\obj\\arm64-v8a",
    "-DCMAKE_BUILD_TYPE\u003dDebug",
    "-DANDROID_NDK\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle",
    "-DCMAKE_SYSTEM_NAME\u003dAndroid",
    "-DCMAKE_ANDROID_ARCH_ABI\u003darm64-v8a",
    "-DCMAKE_SYSTEM_VERSION\u003d21",
    "-DCMAKE_EXPORT_COMPILE_COMMANDS\u003dON",
    "-DCMAKE_ANDROID_NDK\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle",
    "-DCMAKE_TOOLCHAIN_FILE\u003dC:\\Users\\Ariok\\Downloads\\Git\\citra_android\\Sdk\\ndk-bundle\\build\\cmake\\android.toolchain.cmake",
    "-G Ninja",
    "-DANDROID_STL\u003dc++_static",
    "-DENABLE_QT\u003d0",
    "-DENABLE_SDL2\u003d0",
    "-DENABLE_WEB_SERVICE\u003d0",
    "-DANDROID_ARM_NEON\u003dtrue",
    "-DENABLE_CUBEB\u003d0"
  ]
}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"CMake Error: CMake was unable to find a build program corresponding to \"Ninja\".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.","title":"Error","type":"message"}

]== "CMake Server" ==]

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.


[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","progressCurrent":1000,"progressMaximum":1000,"progressMessage":"Configuring","progressMinimum":0,"type":"progress"}

]== "CMake Server" ==]



[== "CMake Server" ==[

{"cookie":"","inReplyTo":"configure","message":"Configuring incomplete, errors occurred!\nSee also \"C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log\".","type":"message"}

]== "CMake Server" ==]

Configuring incomplete, errors occurred!
See also "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".
Configuring incomplete, errors occurred!
See also "C:/Users/Ariok/Downloads/Git/citra_android/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".


[== "CMake Server" ==[

{"cookie":"","errorMessage":"Configuration failed.","inReplyTo":"configure","type":"error"}

]== "CMake Server" ==]

Configuration failed.
External native generate JSON debug: JSON generation completed with problems


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:generateJsonModelDebug'.
> com.android.ide.common.process.ProcessException: Error configuring

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
16 actionable tasks: 1 executed, 15 up-to-date

**Comment by SachinVin** [comment]
@zpoo32 
Apologies for the bad build instructions.
Just download ninja and add it to your path

**Comment by niansa** [comment]
Use pastebin...

**Comment by nkirankumar12** [comment]
I'm seeing the same issue. Can anyone help
