### ISSUE TITLE
Input lag and just lag

### ISSUE THREAD

**Issue by wesleyvanneck** [SachinVin/citra_android#28]
It's for a early build working exynos Samsung s8 plus good fps isn't that bad like for experiment build but is there a way for tweaking it to get a better frame rate

**Comment by wesleyvanneck** [comment]
the thing to get it working to fix the black screen issue use the user file of pc citra thing or 3ds

**Comment by DarkXLord20** [comment]
How to use it ?and how to get more fps only get 1 and very rare up to 5 fps

**Comment by wesleyvanneck** [comment]
i got 8 to 7 fps on old build
try the new buidl
