### ISSUE TITLE
Citra crashes after i choose a game

### ISSUE THREAD

**Issue by mrxrnzl** [SachinVin/citra_android#30]
Whenever i open games like Pokemon, Zelda or Mario citra emulator crashes.
Phone: Alcatel Flash plus 2
OS: marshmallow
Version: 6.0

**Comment by AlvinZp** [comment]
Make sure the GPU support the Citra.What I know is Mali and Snapdragon is not supported.

**Comment by KuyaJowell** [comment]
Lol snapdragon works just fine, make sure its decrypted for citra, the rom is

**Comment by SachinVin** [comment]
@mrxrnzl Logs please does your GPU support Open GL ES 3.2

**Comment by mrxrnzl** [comment]
@SachinVin
My phone only renders open GL ES 3.0 But that dolphin emulator works flawlessly in my phone. I can play gamecube pretty fine on my phone. For logs may I know where to get it? And by the way congratulation on the merge with the original citra team ^^ i hope i can patron you guys soon and i hope this 3ds emulator will be a reality and not a dream. Because way back before nds was a dream and team drastic made its way i hope you guys can make it.
