### ISSUE TITLE
Wont load games

### ISSUE THREAD

**Issue by kidpoisen** [SachinVin/citra_android#31]
When I try to play new mario kart 7, it doesnt move from the tire moving screen

**Comment by AlvinZp** [comment]
Make sure the GPU support the Citra.What I know is Mali and Snapdragon is not supported

**Comment by kidpoisen** [comment]
I have a galaxy is s8, can that support it

**Comment by wesleyvanneck** [comment]
@kidpoisen  I have s8 plus and it works with low fps

**Comment by calebjosephchambers** [comment]
The roms have to be decrypted
