### ISSUE TITLE
Game crash when opening rom

### ISSUE THREAD

**Issue by cupkejk** [SachinVin/citra_android#33]
My game jus crash when im opening rom here ia log: [   0.020256] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   0.020297] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   0.043509] Core <Warning> core/core.cpp:Init:162: CPU JIT requested, but Dynarmic not available
[   0.044569] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:39: AudioCore::SelectSink given invalid sink_id 
[   0.070788] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:544: GL_VERSION: OpenGL ES 3.1 v1.r15p0-00rel0.bdd9e62cdc8c88e0610a16b5901161e9
[   0.070817] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:545: GL_VENDOR: ARM
[   0.070833] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:546: GL_RENDERER: Mali-T720
[   0.088922] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:47: Error compiling fragment shader:
0:4: P0003: Warning: Extension 'GL_ANDROID_extension_pack_es31a' not supported
0:14: L0003: Keyword 'samplerBuffer' is reserved
[   0.088963] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:48: Shader source code:
#version 310 es

#ifdef GL_ES
#extension GL_ANDROID_extension_pack_es31a : enable
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
precision highp samplerBuffer;
#else
precision mediump float;
precision mediump samplerBuffer;
#endif // GL_FRAGMENT_PRECISION_HIGH
#endif // GL_ES

uniform samplerBuffer tbo;
uniform vec2 tbo_size;
uniform vec4 viewport;

out vec4 color;

void main() {
    vec2 tbo_coord = (gl_FragCoord.xy - viewport.xy) * tbo_size / viewport.zw;
    int tbo_offset = int(tbo_coord.y) * int(tbo_size.x) + int(tbo_coord.x);
    color = texelFetch(tbo, tbo_offset).rabg;
}

[   0.089018] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadProgram:84: Error linking shader:
Link failed because of invalid fragment shader.
[   0.089288] Debug <Critical> video_core/renderer_opengl/gl_shader_util.cpp:operator():88: Assertion Failed!
Shader not linked

**Comment by SachinVin** [comment]
@cupkejk 
Your GPU is not supported
