### ISSUE TITLE
Emulator crashes upon loading game

### ISSUE THREAD

**Issue by arvintateyu** [SachinVin/citra_android#36]
Hi,

I have a samsung s8+ and i tried running either Kingdom Hearts 3D or Pokemon Ultra Sun on citra. My specs are ARMv8 x64 and OpenGL ES 3.2. And my games say they have been decrypted for citra. I'm not sure why it crashes. Hope you could help me here

**Comment by Priyam005** [comment]
@arvintateyu you might need to grab your user folder

**Comment by arvintateyu** [comment]
Grab user folder?

**Comment by Priyam005** [comment]
You must have dumped your user folder for your 3ds..

**Comment by arvintateyu** [comment]
I don't think i did since i got the decrypted files without decrypting them. or do i have to decrypt them myself?

**Comment by arvintateyu** [comment]
And when I tried the same files in the PC version, they worked well

**Comment by SachinVin** [comment]
@Priyam005 Cany you give me logs 
they're in [internal storage]/citra-emu/logs

**Comment by SachinVin** [comment]
@arvintateyu It looks like you have a mali GPU. It's not supported at the moment.Look at #8
