### ISSUE TITLE
Error doing a full recursive clone of the backend

### ISSUE THREAD

**Issue by mascondante** [SachinVin/citra_android#39]
`git pull --recurse-submodules -j8 https://github.com/SachinVin/citra.git` results in:

`error: Server does not allow request for unadvertised object 4b350a354a21339052c7fff88832c3f81f5624be
Fetched in submodule path 'externals/dynarmic', but it did not contain 4b350a354a21339052c7fff88832c3f81f5624be. Direct fetching of that commit failed.`

**Comment by SachinVin** [comment]
@mascondante Thanks for reporting,it's fixed ...i think. Can you try again?

**Comment by mascondante** [comment]
After deleting the old copy and cloning fresh I was able to get it to work. That's good enough for me. I appreciate it. Not sure where else say this so I'll have to thanks for your efforts here. The community appears in thrilled uproar and even though I don't quite have a cutting edge phone to work with I'm still really happy to just see 3DS games booting and getting to play around with them even if in just a limited capacity.
