### ISSUE TITLE
Game crash when opening rom

### ISSUE THREAD

**Issue by reaper797XY** [SachinVin/citra_android#40]
My log 

[   1.123549] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   1.123571] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   1.136869] Core <Warning> core/core.cpp:Init:162: CPU JIT requested, but Dynarmic not available
[   1.137239] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:39: AudioCore::SelectSink given invalid sink_id 
[   1.164782] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:544: GL_VERSION: OpenGL ES 3.1 V@145.0 (GIT@I88e9891e40)
[   1.164806] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:545: GL_VENDOR: Qualcomm
[   1.164810] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:546: GL_RENDERER: Adreno (TM) 530
[   1.166952] Render.OpenGL <Error> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:527: API ERROR 2147483647: unable to enable capability %d because it is an invalid enum

**Comment by yoroxx101** [comment]
Same problem here.

**Comment by reaper797XY** [comment]
Log after changing Open GL version

https://drive.google.com/open?id=1ww2emiSz8UqeaDtq-kZr8OBshGIpfQdF

ROM opens but only black screen

**Comment by reaper797XY** [comment]
# kenan 1099
It works on other snapdragon 820 phone and not mine , while both have same adreno 530

**Comment by reaper797XY** [comment]
Updated to the latest graphic drivers and it works now.... Thank you guys....
