### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by mildtemp** [SachinVin/citra_android#44]
Can you identify if my Android is capable of playing using Citra? Here is a screenshot of specs of my Android: [Screenie](https://drive.google.com/file/d/1kABOb_zFTaW7M5vvL0r00t1l_rDoc63i/view?usp=sharing)

Here is my log: [citra_log.txt](https://drive.google.com/file/d/12wNJFmBHoC2DNgDybA1RNN8LYuwl446U/view?usp=sharing)

Also, can you teach us how to identify if our Android is not supported by reading the logs? For future users who will look into this problem if they encounter this specific issue. Thank you in advance!

**Comment by wesleyvanneck** [comment]
@mildtemp  no it dosnt support it

**Comment by SachinVin** [comment]
@mildtemp You can see that your phone doesn't support gles 3.2
