### ISSUE TITLE
log

### ISSUE THREAD

**Issue by azoa9** [SachinVin/citra_android#46]
[   0.040640] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay[   0.040716] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()[   0.070990] Core <Warning> core/core.cpp:Init:165: CPU JIT requested, but Dynarmic not available[   0.079028] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:40: AudioCore::SelectSink given invalid sink_id [   0.256808] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:307: ClCertA file missing[   0.264183] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:568: GL_VERSION: OpenGL ES 3.1 V@145.0 (GIT@Ia3ef73d9d4)[   0.264314] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:569: GL_VENDOR: Qualcomm[   0.264655] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:570: GL_RENDERER: Adreno (TM) 505[   0.315505] Render.OpenGL <Warning> video_core/renderer_opengl/gl_rasterizer.cpp:RasterizerOpenGL:54: Shadow might not be able to render because of unsupported OpenGL extensions.[   0.315590] Render.OpenGL <Warning> video_core/renderer_opengl/gl_rasterizer.cpp:RasterizerOpenGL:59: ARB_texture_barrier not supported. Some games might produce artifacts.[   0.319221] Render.OpenGL <Error> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:551: API ERROR 2147483647: unable to enable capability %d because it is an invalid enum

**Comment by SachinVin** [comment]
Your phone doesnt support gles 3.2
