### ISSUE TITLE
citra log

### ISSUE THREAD

**Issue by azoa9** [SachinVin/citra_android#47]
0.023567] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay[   0.023604] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()[   0.040843] Core <Warning> core/core.cpp:Init:162: CPU JIT requested, but Dynarmic not available[   0.041929] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:39: AudioCore::SelectSink given invalid sink_id [   0.064610] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:544: GL_VERSION: OpenGL ES 3.1 V@145.0 (GIT@Ia3ef73d9d4)[   0.064638] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:545: GL_VENDOR: Qualcomm[   0.064645] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:546: GL_RENDERER: Adreno (TM) 505[   0.102474] Render.OpenGL <Error> video_core/renderer_opengl/renderer_opengl.cpp:DebugHandler:527: API ERROR 2147483647: unable to enable capability %d because it is an invalid enum

**Comment by azoa9** [comment]
My mobile phone crashed when I entered it. This is the log,I hope I can help you.

**Comment by SachinVin** [comment]
@azoa9 But I already told you in #46...
