### ISSUE TITLE
About the CPU

### ISSUE THREAD

**Issue by XIONGCHUMMO** [SachinVin/citra_android#49]
My CPU is Hisilicon Kirin 925. Can I run the game?

**Comment by XIONGCHUMMO** [comment]
My running memory is 3gb.The android version is 6.0.But I click on the ROM but it can not run, will carton, and finally forced off, is the compatibility issue?What should I do?

**Comment by M220** [comment]
No, See #8

**Comment by XIONGCHUMMO** [comment]
Thank
