### ISSUE TITLE
[Question]Why dont work in 32bits?

### ISSUE THREAD

**Issue by JunioJsv** [SachinVin/citra_android#5]
My mediatek is 64bits, but systen run in 32 bits mode.

**Comment by SachinVin** [comment]
You can try, if your device supports GLES 3.2 it might work.

**Comment by JunioJsv** [comment]
@SachinVin yes, support

**Comment by SachinVin** [comment]
Then you can try

**Comment by JunioJsv** [comment]
@SachinVin the emulator crash on run the rom

**Comment by abowalid1432** [comment]
Yeah it's happening to me. What to do now ?
________________________________

**Comment by davyson441** [comment]
Amigos o meu abre e fecha quando eu abro a rom. O meu celular e um g5s
