### ISSUE TITLE
Huawei crash

### ISSUE THREAD

**Issue by NOWIXX** [SachinVin/citra_android#50]
Hello, my Huawei y6 crash when I run the rom file (excuse me faults I'm speak in French)  the logs: [   0.036194] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   0.036226] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   0.149182] Core <Warning> core/core.cpp:Init:162: CPU JIT requested, but Dynarmic not available
[   0.152280] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:39: AudioCore::SelectSink given invalid sink_id 
[   0.189342] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:544: GL_VERSION: OpenGL ES 3.0 V@251.0 AU@08.00.00.312.030 (GIT@Ie4790512f3)
[   0.189375] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:545: GL_VENDOR: Qualcomm
[   0.189382] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:546: GL_RENDERER: Adreno (TM) 308
[   0.220501] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:47: Error compiling fragment shader:
Fragment shader compilation failed.
WARNING: 0:4: extension 'GL_ANDROID_extension_pack_es31a' is not supported
ERROR: 0:7: ';' : Syntax error:  syntax error
ERROR: 1 compilation errors.  No code generated.

[   0.220528] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:48: Shader source code:
#version 300 es

#ifdef GL_ES
#extension GL_ANDROID_extension_pack_es31a : enable
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
precision highp samplerBuffer;
#else
precision mediump float;
precision mediump samplerBuffer;
#endif // GL_FRAGMENT_PRECISION_HIGH
#endif // GL_ES

uniform samplerBuffer tbo;
uniform vec2 tbo_size;
uniform vec4 viewport;

out vec4 color;

void main() {
    vec2 tbo_coord = (gl_FragCoord.xy - viewport.xy) * tbo_size / viewport.zw;
    int tbo_offset = int(tbo_coord.y) * int(tbo_size.x) + int(tbo_coord.x);
    color = texelFetch(tbo, tbo_offset).rabg;
}

[   0.220790] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadProgram:84: Error linking shader:
Invalid fragment shader. Link cannot proceed.

[   0.220805] Debug <Critical> video_core/renderer_opengl/gl_shader_util.cpp:operator():88: Assertion Failed!
Shader not linked

**Comment by M220** [comment]
#8

**Comment by wesleyvanneck** [comment]
Your opengl es is to low

**Comment by SachinVin** [comment]
what @wesleyvanneck said
