### ISSUE TITLE
Need to work on mediatek helio P60 support

### ISSUE THREAD

**Issue by Priyam005** [SachinVin/citra_android#52]
Earlier I had a SD 636 phone with 4gb ram and no vulkan support but now I switched to a phone with mediatek helio P60 6gb ram and vulkan support too but citra won't work here..
And it literally didn't even make any logs..
Here are some detailed specifications and my phone is oppo realme 1
![img_20181028_105553](https://user-images.githubusercontent.com/43999863/47612462-f1bb3300-daa0-11e8-9b1e-90e2e1723e2a.jpg)
![img_20181028_105607](https://user-images.githubusercontent.com/43999863/47612463-f1bb3300-daa0-11e8-9c35-9959d1e42195.jpg)
![img_20181028_105626](https://user-images.githubusercontent.com/43999863/47612464-f2ec6000-daa0-11e8-99ee-533be8bb83c6.jpg)

**Comment by SachinVin** [comment]
same issue as #8
