### ISSUE TITLE
Best configuration for playing Pokemon Ultra Sun

### ISSUE THREAD

**Issue by hkpanchal** [SachinVin/citra_android#53]
I've various combinations while playing Pokemon Ultra Sun but still the graphics of the game doesn't improve. Can someone share the best configuration so that we all can try. Thanks

**Comment by Priyam005** [comment]
@hkpanchal if you want to get better graphics then just change the 'resolution_factor' value (1 being the lowest and 9 being the highest) in sdl2-config.ini which is located in citra-emu folder in your internal storage.. I would recommend you to keep at 4 but it's your choice...

**Comment by hkpanchal** [comment]
Thanks Priyam005, I would try and update regarding the experience after changing the value.

**Comment by hkpanchal** [comment]
Results remain the same. In fact it becomes more slow. I'm using Redmi Note 3.

**Comment by hkpanchal** [comment]
![screenshot_2018-10-28-18-22-30-857_org citra citra_android](https://user-images.githubusercontent.com/44546670/47616143-a3ae2b80-dab0-11e8-8aac-65b5f75ebd9a.png)
Please check the screenshot for the reference

**Comment by Priyam005** [comment]
That's very wierd could you please upload your configuration file?

**Comment by DarkXLord20** [comment]
Does citra working on exynos s8?

**Comment by hkpanchal** [comment]
I'm sorry, it's giving an error, when I'm trying to attach the file. Can you share your's so that I can replace mine?

**Comment by SachinVin** [comment]
@hkpanchal Can i see the logs they're in internal storage/citra-emu/logs

**Comment by hkpanchal** [comment]
[citra_log.txt](https://github.com/SachinVin/citra_android/files/2526890/citra_log.txt)
Hope this helps

**Comment by hkpanchal** [comment]
Here is the configuration file. I've changed the extension to attach it here
[sdl2-config.txt](https://github.com/SachinVin/citra_android/files/2526912/sdl2-config.txt)

**Comment by hkpanchal** [comment]
Still waiting for someone to share the best configuration so we all can try

**Comment by SachinVin** [comment]
> Still waiting for someone to share the best configuration so we all can try
@hkpanchal there isn't any.

**Comment by wesleyvanneck** [comment]
sorry mate but it plays bad on s8 plus

**Comment by KillerModdX** [comment]
@hkpanchal Ultra sun is bad like hell It gives a constant 10 FPS on my OP6 whereas Omega Ruby gives 20 to 22 constantly during battles and towns or cities and 30 fps when inside a building. You should give up on Ultra sun for now and wait for emulator to get better.
