### ISSUE TITLE
Crashed on exynos s8

### ISSUE THREAD

**Issue by DarkXLord20** [SachinVin/citra_android#54]
Does it work on exynos s8 and if yes how?
Everytime I try to load rom it crashes

**Comment by DarkXLord20** [comment]
Now get it work but very slow how to increase speed?

**Comment by DarkXLord20** [comment]
How to use the trick with citra user pc file?

**Comment by DarkXLord20** [comment]
And is there a way to get newer version of citra

**Comment by SachinVin** [comment]
same issue as #8
