### ISSUE TITLE
Still crashes and exits to menu v0.5.1

### ISSUE THREAD

**Issue by Blight-kun** [SachinVin/citra_android#56]
The update still giving the same results except it can run on my J2 Prime (Mediatek MT6737T) but crashes at the loading phase, before it crashes all the key buttons gathered at the top left of the screen and also on my Snapdragon 415, Adreno 305 crashes the same as v0.4.1

**Comment by SachinVin** [comment]
@Blight-kun that is because Your phone doesn't suppor GLES 3.2
