### ISSUE TITLE
G5s 

### ISSUE THREAD

**Issue by davyson441** [SachinVin/citra_android#57]
Sashin vin o meu celular e um G5s ele tem o gls de 3.2. mais quando eu abro um jogo ele trava. O que será isso. Obg

**Comment by SachinVin** [comment]
@davyson441 can you say that in English?

**Comment by SachinVin** [comment]
@davyson441 can I get logs from internal storage/citra-emu/logs.

**Comment by davyson441** [comment]
Yes

**Comment by davyson441** [comment]
Yes

**Comment by davyson441** [comment]
sashin vin what should i do now friend

**Comment by davyson441** [comment]
sashin vin what should i do now friend

**Comment by SachinVin** [comment]
upload logs from  internal_storage/citra-emu/logs

**Comment by davyson441** [comment]
load logs in the emulator ????

**Comment by davyson441** [comment]
sachin vin friend send me an app prrparado for this please friend obg

**Comment by SachinVin** [comment]
Upload the logs here

**Comment by davyson441** [comment]
sashin vin says that this link is not valid friend

**Comment by davyson441** [comment]
sachin vin I downloaded the last update friend and still the same error continues. that speaks. CITRA HAS STOPPED TO WORK

**Comment by SachinVin** [comment]
@davyson441 I can't help you if you don't give me logs

**Comment by davyson441** [comment]
sachin vin the link that you sent me says that it is not valid in my account.

**Comment by davyson441** [comment]
[  33.727489] Frontend <Info>
citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52:
InitDisplay
[  33.727527] Frontend <Info>
citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[  33.779778] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175:
Secure1 KeyX missing
[  33.779825] Service.FS <Warning>
core/file_sys/ncch_container.cpp:Load:271: NCCH is marked as encrypted but
with decrypted exheader. Force no crypto scheme.
[  33.780914] Core <Warning> core/core.cpp:Init:165: CPU JIT requested, but
Dynarmic not available
[  33.784775] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:40:
AudioCore::SelectSink given invalid sink_id
[  33.789761] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:45:
Error getting minimum latency
[  33.827155] Service.HTTP <Error>
core/hle/service/http_c.cpp:DecryptClCertA:307: ClCertA file missing


Em seg, 29 de out de 2018 13:52, SachinVin <notifications@github.com>
escreveu:

**Comment by M220** [comment]
There's a folder in your phone storage named Citra_emu, go to that folder, there's another folder within that Citra_emu folder named log, and there is a txt file named "citra_log", you have to upload that here, you can upload it in upload services like drive OR You can go to chrome browser and check the "Desktop site" checkbox from when You are here in this page and select "Selecting them" in the bottom of this page ( bottom of the box that says "leave a comment") then navigate to that file that I said you sould upload and select it, wait a little and then there will be a link in the "leave your comment" box, at last, tap the comment button

**Comment by davyson441** [comment]
[citra_log.txt](https://github.com/SachinVin/citra_android/files/2526533/citra_log.txt)

**Comment by davyson441** [comment]
sachin vin friend the new one I downloaded it the same way you know. I would like to know what day you will update it again. THX.

**Comment by davyson441** [comment]
![screenshot_20181031-161229](https://user-images.githubusercontent.com/43894246/47812697-de6dc900-dd27-11e8-9bc7-193072610d10.png)

**Comment by EscanorXX** [comment]
His original post says "Hey @SachinVin, my phone is the `G5s` and it has the OpenGL 3.2, despite that, when i open any game, it lags. Why is it happening?

Thanks.

@davyson441 Mano, tens que esperar mais tempo, ese emulador tá em fase de testes. O necessário para que possa jogar dum modo fluido e tiver um móvel com Snapdragon 845 o um superior, a parte de tiver OpenGL 3.2. Eu te recomendo esperar até Dezembro, e voltar a preguntar sobre isso.

**Comment by Ae3NerdGod** [comment]
Dolphin requires a 64 bit OS build, if I am correct in assuming citra does also, then that's why the g5s won't work, the stock is is 32 bit despite having a 64 bit processor, and any "64 bit" builds treble or otherwise for the g5s are missing a good chunk of 64 bit driver code from what I remember reading. 

But again, if citra should run on 32 bit OS then everything I've said is immaterial

**Comment by davyson441** [comment]
sashivin and citra Android will still be developed ???

Em qui, 7 de mar de 2019 22:12, Ae3NerdGod <notifications@github.com>
escreveu:
