### ISSUE TITLE
cant open up a game

### ISSUE THREAD

**Issue by da-tokkies** [SachinVin/citra_android#6]
device: oneplus 5t
os: android 8.1

if i want to add a game i dont see the game as an option.
its a .3ds file decrypted for citra and it works on pc

**Comment by SachinVin** [comment]
Click the Floating Plus(+) button on the bottom left, then navigate and select the folder in which the .3ds file is in

**Comment by davyson441** [comment]
Amigo quando abro um jogo da o seguinte erro: falhas na continuidade. Que erro e esse

**Comment by thepuremilk** [comment]
My device is Vivo Y71
The game that I've tried is Kingdom Hearts DDD (decrypted)

I already add the game in my phone, but when tried to open, it's always crash or go back to my home screen again. Can you help me explain why?

Thank-you

**Comment by SachinVin** [comment]
@davyson441 can you say that in English please
@thepuremilk mali gpus arent supported

**Comment by thepuremilk** [comment]
But my gpus is qualcomm andreno bro :(

**Comment by SachinVin** [comment]
sorry, can you give logs
they are in [internal storage]/citra-emu/logs

**Comment by thepuremilk** [comment]
[citra_log.txt](https://github.com/SachinVin/citra_android/files/2452774/citra_log.txt)

That's my log bro, hope you can figure it out. BTW thank you so much

**Comment by SachinVin** [comment]
@thepuremilk your GPU not supported
