### ISSUE TITLE
Mali and the Snapdragon

### ISSUE THREAD

**Issue by Rhomylos** [SachinVin/citra_android#61]
Do Mali and the Snapdragon work? will be supported in the future?

**Comment by Playingaim** [comment]
Snapdragon works while everything else doesn't but I can confirm mali GPUs have sound this time

**Comment by Playingaim** [comment]
So I can confirm some games run with mail GPUs I tested a few games so far

**Comment by SachinVin** [comment]
Adreno works and mali seems to be working, you can try it out and report any issues
