### ISSUE TITLE
Cloudfone Excite c

### ISSUE THREAD

**Issue by Lex730** [SachinVin/citra_android#64]
pls help me why citra emulator is not running on my android and plss fix it I want to play pokemon ultra sun.....
this is my Log plss..I hope next update it will run properly on my android phone:

[   0.478614] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   0.478649] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   0.518291] Core <Warning> core/core.cpp:Init:165: CPU JIT requested, but Dynarmic not available
[   0.521338] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:40: AudioCore::SelectSink given invalid sink_id 
[   0.522084] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:45: Error getting minimum latency
[   0.611260] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:307: ClCertA file missing
[   0.642547] Frontend <Error> citra_android/jni/ndk_helper/GLContext.cpp:Resume:226: Unable to eglMakeCurrent 12297

**Comment by Emulatorer** [comment]
Cloudfone Excite Prime 2 Pro with Snapdragon 430 Adreno 506 can't even run smooth in dolphin emulator so what do expect in a 3ds emulator?

Which required higher specs to run some games smoothly :/

But first what Cloudfone Excite are you using?

**Comment by Lex730** [comment]
I hope this emulator can run any android phone smoothly...I Hope It soon..I trust also the creator of this app that he can fix it so that many people can use this emulator in any kind of android phone...😇😇like the nds emulator some nds emulator run slowly but the drastic can run the nds rom in any kind of android phone smoothly...

**Comment by Emulatorer** [comment]
That's impossible to happen Drastic is a NDS emulator and yes almost all games can run smoothly even in a low specs android but do not compare Citra 3ds emulator it's required higher OpenGL version like OpenGL 3.1+ unlike Drastic OpenGL 2.0 is enough better to buy a higher specs phone :/

Sana na gets moko haha 😀👍

**Comment by Lex730** [comment]
ah!!so wala na talaga syang pag-asang gumana sa lahat ng android phone at kaylangan ko nang bumili ng bago??ano ba magandang phone??

**Comment by Lex730** [comment]
salamat!...

**Comment by Lex730** [comment]
okey ba ung xiaomi redmi s2

**Comment by Emulatorer** [comment]
ok naman yang redmi s2 pero di pasok yan pang 3Ds, PS2 at Dolphin emulator

**Comment by Lex730** [comment]
suggest ka nga ng cellphone na medyo mura na maganda pang 3ds,PS2 at dolphin emu..plss

**Comment by Emulatorer** [comment]
Pocofhone f1

**Comment by Emulatorer** [comment]
@Lex730 close mo na to not related sa main issue ng 3Ds emulator to :)

**Comment by Lex730** [comment]
okey salamat sa info at help mo...
