### ISSUE TITLE
Low FPS & SPEED

### ISSUE THREAD

**Issue by Karthigeyan21** [SachinVin/citra_android#66]
Is There Anyway To Get 20+ FPS ? I Always End Up With 3-5 FPS ...

**Comment by Emulatorer** [comment]
Buy highend android phone like Xiaomi BlackShark 2 or ASUS ROG Phone
and what do you expect from a alpha stage 3ds emulator :/

**Comment by wesleyvanneck** [comment]
Every one have this issue but you need a stronger device to run it smooth but you don't need buy phone that cost thousands dollars etc

**Comment by wesleyvanneck** [comment]
It isn't optimized and its pre release so what do expect  of it
