### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by TechBoxTv** [SachinVin/citra_android#76]
Can you impliment the Drastic Mask to it?

**Comment by SachinVin** [comment]
What do you mean? You have a screenshot or something ?

**Comment by Hargeehey** [comment]
@SachinVin maybe he is trying to say is this

**Comment by SachinVin** [comment]
I don't get it...

**Comment by Hargeehey** [comment]
Hmm... Oh sorry
Maybe he is trying to say that can you make the Drastic emulator's features and options implement to your citra?

(A little hard to explain hehehe)

**Comment by Hargeehey** [comment]
@SachinVin

**Comment by TechBoxTv** [comment]
I mean the overlay of the emulator instead of the dolphin Mask using this
one and maybe implement the setting and menu

Hargeehey <notifications@github.com> schrieb am Mo., 5. Nov. 2018, 11:40:

**Comment by TechBoxTv** [comment]
Ok thank You for Quick Response, Do you know if the speed on the exynos
Version can be fixed?

SachinVin <notifications@github.com> schrieb am Mo., 5. Nov. 2018, 15:25:

**Comment by SachinVin** [comment]
Likely when dynarmic gets an arm backend
