### ISSUE TITLE
Pokemon omega ruby wont open

### ISSUE THREAD

**Issue by iSayain** [SachinVin/citra_android#78]
I added Pokemon or to my app and I open the Rom but it gives a black screen the crashes...here's the log:
[   7.401846] Frontend <Info> citra_android/jni/emu_window/emu_window.cpp:EmuWindow_Android:52: InitDisplay
[   7.401894] Frontend <Info> citra_android/jni/ndk_helper/GLContext.cpp:Init:78: GLContext Init()
[   7.464918] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:175: Secure1 KeyX missing
[   7.464976] Service.FS <Error> core/file_sys/ncch_container.cpp:Load:189: Secure2 KeyX missing
[   7.465000] Service.FS <Warning> core/file_sys/ncch_container.cpp:Load:271: NCCH is marked as encrypted but with decrypted exheader. Force no crypto scheme.
[   7.466876] Core <Warning> core/core.cpp:Init:165: CPU JIT requested, but Dynarmic not available
[   7.472769] Audio <Error> audio_core/sink_details.cpp:GetSinkDetails:40: AudioCore::SelectSink given invalid sink_id 
[   7.481260] Audio.Sink <Critical> audio_core/cubeb_sink.cpp:CubebSink:45: Error getting minimum latency
[   7.579906] Service.HTTP <Error> core/hle/service/http_c.cpp:DecryptClCertA:307: ClCertA file missing
[   7.583091] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:568: GL_VERSION: OpenGL ES 3.1 v1.r15p0-00rel0.98e69a4d293675cb3e24ddfee048abf6
[   7.583150] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:569: GL_VENDOR: ARM
[   7.583169] Render.OpenGL <Info> video_core/renderer_opengl/renderer_opengl.cpp:Init:570: GL_RENDERER: Mali-T720
[   7.629083] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:47: Error compiling fragment shader:
0:4: P0003: Warning: Extension 'GL_ANDROID_extension_pack_es31a' not supported
0:14: L0003: Keyword 'samplerBuffer' is reserved
[   7.629164] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadShader:48: Shader source code:
#version 310 es

#ifdef GL_ES
#extension GL_ANDROID_extension_pack_es31a : enable
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
precision highp samplerBuffer;
#else
precision mediump float;
precision mediump samplerBuffer;
#endif // GL_FRAGMENT_PRECISION_HIGH
#endif // GL_ES

uniform samplerBuffer tbo;
uniform vec2 tbo_size;
uniform vec4 viewport;

out vec4 color;

void main() {
    vec2 tbo_coord = (gl_FragCoord.xy - viewport.xy) * tbo_size / viewport.zw;
    int tbo_offset = int(tbo_coord.y) * int(tbo_size.x) + int(tbo_coord.x);
    color = texelFetch(tbo, tbo_offset).rabg;
}

[   7.629258] Render.OpenGL <Error> video_core/renderer_opengl/gl_shader_util.cpp:LoadProgram:84: Error linking shader:
Link failed because of invalid fragment shader.
[   7.629944] Debug <Critical> video_core/renderer_opengl/gl_shader_util.cpp:operator():88: Assertion Failed!
Shader not linked

**Comment by SachinVin** [comment]
Your phone doesn't support gles 3.2
