### ISSUE TITLE
Three dot menu 

### ISSUE THREAD

**Issue by Guns29** [SachinVin/citra_android#79]
Hello I have found a bug on my gs8 when sliding the menu down I can't see the 3 dot menu but when opening the gs8 side bar then closing it then menu button. Shows not sure what's going on but even with dolphine emu does the same thing

**Comment by DarkXLord20** [comment]
For me it works I don't know how I did it but I had this problem too

**Comment by DarkXLord20** [comment]
Do you have a point on the left site from navigation bar? If yes tap twice then it works

**Comment by Guns29** [comment]
No if I open the side bar then close it the menu button shows or if I minimize the emu then restore it it will show up other then that it won't especially when I open the emu it won't so not sure if it has to do with the side bar but yea

**Comment by Guns29** [comment]
Also to point out that while in landscape mode I have to minimize the emu then reopen it to show the menu but in portrait mode I can open the side bar or minimize the emu to show the menu button so it crazy

**Comment by DarkXLord20** [comment]
Which phone you have exactly?

**Comment by Guns29** [comment]
Galaxy s8

**Comment by DarkXLord20** [comment]
![20181107_065549](https://user-images.githubusercontent.com/44550503/48113238-4c4f4e80-e25a-11e8-9ba0-6521d66b8e9f.jpg)
Press this button on navigation bar

**Comment by Guns29** [comment]
Well that's crazy but yes that's work ha that's nutty thanks alot but shouldn't this be turn on by default and auto hide after double tapping the dot

**Comment by Guns29** [comment]
Thanks alot for this

**Comment by DarkXLord20** [comment]
No problem

**Comment by Guns29** [comment]
In the future will the menu be on auto or do we have to enable manually

**Comment by DarkXLord20** [comment]
I've no idea

**Comment by Guns29** [comment]
Can't wait to see updates I glad some one stepped up and port citra if I new how to do stuff like this I would lol
