### ISSUE TITLE
In-game time and date

### ISSUE THREAD

**Issue by wannabeGDNR** [SachinVin/citra_android#82]
Hello,
First of all I would like to thank you guys for all the wonderful work. 
Game: Pokemon UM
Device:Lg G5
I know this is probably not a top priority issue for know, but can the ingame date and time be fixed? (It always gets reset to 01/01/2000 0:00 after restarting the game). In game stopwatch (I meant the gameplay duration) seems to be working fine though.
Also can snapdragon 820 be expected to run 10+ fps in future as emulator gets better?

**Comment by HelloOO7** [comment]
I looked at some benchmarks of the SD 820 and it's near an i3-3110M with integrated graphics, and I just so happen to have one of those. Now will it be able to run above 10 FPS? My i3 laptop runs it at 30 with some drops, but that's after more than 5 years of development, with a dynarec and pretty advanced hardware renderer (which has only been added like 6 months ago). A SD 820 will probably run it "fine" in a few years, but do you really want to play 3DS games with touchscreen controls? The purpose of emulators is to play games at higher/unlocked by mods framerates, upscaled and with any controller you want. Considering even the best phones out there are struggling to maintain 20 FPS on native resolution and you are asking if your phone can hit TEN, then what's the point? Just play on your 3DS for the time being.

**Comment by wannabeGDNR** [comment]
Thanks man! It's fixed. I never thought that solution will be that simple!

**Comment by HelloOO7** [comment]
Wait, so you changed the value in config and it works? That's nice! I'll try making a modded version that does this by default and upload it here, could you please test it then (I don't have a device capable of running Citra)? If it works, I'll make a PR and try to merge it into the official build.

**Comment by wannabeGDNR** [comment]
Sure I will!

**Comment by HelloOO7** [comment]
Here it is! Fingers crossed it does something...

[Citra.FixedDate.apk.zip](https://github.com/SachinVin/citra_android/files/2558935/Citra.FixedDate.apk.zip)

**Comment by wannabeGDNR** [comment]
I used the same savefile.
Now the time and date are same as that of system by default(you did it!), but the speed was decreased to unplayable levels (fps-0.6, 2%). The main apk has 'playable' speed(fps-3.4 to 7) but has fixed time and date by default. Please correct me if I have made any mistake while testing.

**Comment by SachinVin** [comment]
I think defaulting to 1 was unintended as the ini file itself states that the default should be 0 (System
clock)

**Comment by SachinVin** [comment]
It does run with hardware renderer on GLES 3.2 devices only tho.
Yeah I guess its best to merge the 0 to official repo.

**Comment by HelloOO7** [comment]
https://github.com/SachinVin/citra/commit/6cdbd7fb60f85aaaeedaa840f5903776be47ff60

PR of what I used for Citra.FixedDate build. @wannabeGDNR said it works for him, so the fix is apparently this simple.

**Comment by SachinVin** [comment]
You should also probably make one for the official citra
