### ISSUE TITLE
Gamepad

### ISSUE THREAD

**Issue by Guns29** [SachinVin/citra_android#90]
Can use implement support for bluetooth I want to use my game pad but does not work

**Comment by SachinVin** [comment]
Can you add these settings to the config.ini file in` internal_storage/citra-emu/config`
and tell me if it works (these are for game pads that used ABXY and not 1234)
```
button_a=engine:gamepad,code:96
button_b=engine:gamepad,code:97
button_x=engine:gamepad,code:99
button_y=engine:gamepad,code:100
button_up=engine:gamepad,code:19
button_down=engine:gamepad,code:20
button_left=engine:gamepad,code:21
button_right=engine:gamepad,code:22
button_l=engine:gamepad,code:102
button_r=engine:gamepad,code:103
button_start=engine:gamepad,code:108
button_select=engine:gamepad,code:109
button_zl=engine:gamepad,code:104
button_zr=engine:gamepad,code:105
```

**Comment by Guns29** [comment]
all but the anylog and digi pad dont work

**Comment by Guns29** [comment]
i see where you going at but y not just implement the button so we can do it in the menu under controller

**Comment by SachinVin** [comment]
Easier said than done, Citra dosent exactly support inputs from multiple sources, so have to figure out an efficient way to switch inputs on the fly , or let the user switch between them manually(not super ideal).
BTW does digi pad mean D pad?

**Comment by Guns29** [comment]
Yes d-pad also I notice the input for .cfg file some are different then the one you gave me is the config same as delphine since this is a front end from dolphin

**Comment by Guns29** [comment]
In dolphin it says the controller name then the input like for example controller name-dpad:01-

**Comment by Guns29** [comment]
do you have a dc (Discord) to help where devs can talk maybe this will help speed up the process

**Comment by Guns29** [comment]
and take a load of your shoulders

**Comment by Guns29** [comment]
Here is the list i think 

CStickDown_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 14+
CStickLeft_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 11+
CStickRight_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 11-
CStickUp_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 14-
DPadDown_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 16+
DPadLeft_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 15-
DPadRight_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 15+
DPadUp_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 16-
InputA_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Button 97
InputB_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Button 96
InputL_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Button 102
InputR_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Button 103
InputStart_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Button 108
InputX_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Button 100
InputY_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Button 99
InputZ_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Button 109
MainDown_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 1+
MainLeft_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 0-
MainRight_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 0+
MainUp_0 = Device 'c3c5e8a9900fdf4623ee3f0c2e4b18e1c9fdd5f2'-Axis 1-

**Comment by SachinVin** [comment]
Ah, makes sense that d pad didnt work , it probably uses hat axis instead of d pad (an input mapper would have made it easier :| ).  I do have a discord you can find me somewhere on citra's.

**Comment by Guns29** [comment]
That's y it's best to have an auto mapper to detect the buttons like dolphin has

**Comment by Guns29** [comment]
Can u provide a link thank you

**Comment by EscanorXX** [comment]
Invite me too Guns29

**Comment by Guns29** [comment]
Ok give me a few just woke up

**Comment by Guns29** [comment]
whats your name in dc

**Comment by Guns29** [comment]
and #number

**Comment by EscanorXX** [comment]
@Guns29 DonAntonio #5007

**Comment by Guns29** [comment]
ok i inv you to me dc  join
