### ISSUE TITLE
Optimisation?

### ISSUE THREAD

**Issue by Jack-Rickwood** [SachinVin/citra_android#92]
Just wondering if these things are/are planned to be implemented. They could probably increase frames.
- Frameskipping. Ik this isnt a thing even in pc citra, but it may be the only way we will be able to get playable fps.
- Multicore. Does citra android utilise multiple cpu cores?
- Downscaling. Is there a way this could be implemented and would it achieve better fps? I tried it manually with gltools, but it just crashes citra.
- Caching shaders to the disk. Dont know if this is a thing or not, but could increase fps. I also tried to do this manually with gltools but no luck.

Also: With dolphin android, changing the emulated cpu clockspeed down to ~35% increases fps by a lot, but i could hardly notice a difference with citra. Do you know why?

**Comment by SachinVin** [comment]
You should direct these questions to the citra team, if anything in the core is going to be implemented it will be implemented over there.
As for emulated clock speed they mean different things on different systems
