### ISSUE TITLE
Rom doesn't load

### ISSUE THREAD

**Issue by DexLionhart** [SachinVin/citra_android#94]
I don't know if this issue is mentioned yet but I'm trying to play Bravely default and have it decrypted and works fine on pc version but when I tried running it on this app on my phone, all it shows is a black screen with frametime fluctuating between 15 ms and speed 95-100%. 

Log: [citra_log.txt](https://github.com/SachinVin/citra_android/files/2592794/citra_log.txt)

**Comment by Guns29** [comment]
Because the Rom is not compatible with the emu member this emu is in its early stages but give it time ok :)

**Comment by DexLionhart** [comment]
Oh okay. I thought I didn't operate it well or it was device's problem. Maybe I'll just wait it out.

**Comment by Guns29** [comment]
no this has nothing to do with phones this is more about optimization and compatibility there are so many bugs with the emu to work out roms just cant load but one of my fav does zelda so im good lol

**Comment by AniXBoX** [comment]
Pokemon sun is working fine but it cant load the rom of pokemon x and pokemon omega ruby.
