### ISSUE TITLE
Fps

### ISSUE THREAD

**Issue by DexLionhart** [SachinVin/citra_android#96]
Hate to come back with an issue but now I'm trying to play Ultra moon and it works but the problem is the fps is incredibly low that it just constantly runs at 2.5 fps not even 15-20 fps. The only time it goes 15 fps is when it is on start menu and rest of the time it remains on 2 fps. 

I'm playing it on my new phone which is not a low end but is considered one of the best in midrange to play games also I personally feel my phone may not be the issue here.

**Device**: ASUS_X00TD
**OS**: Android 8.1
**Processor**: SD SoC 660

**Log**- [citra_log.txt](https://github.com/SachinVin/citra_android/files/2593604/citra_log.txt)

**Comment by Guns29** [comment]
Ok the emu is in development stages and there are plenty of bugs to sort that why the fps is low please give it time i have a gs9 i got today from a gs8 and saw a small percentage go up so this will take time

**Comment by KillerModdX** [comment]
I get constant 10 FPS while playing in the hau'oli City area and during the starting I get 30 fps for few fps and drops again.
I'm using a OnePlus 6 ; SoC : SD 845
